version: '3.8'

services:
  app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    volumes:
      - /c/Users/christian.esposito/Desktop/metadati  # Monta l'intera directory "Project"
    environment:
      - UPLOAD_DIR=/app/data  # Ora punta alla cartella "Project"
      - MONGO_URI=mongodb://mongo:27017/metadati
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
